### PR TITLE
have modified every scroll physics  with a BouncingScrollPhysics

### PR DESCRIPTION
**Pull request by Codesait**
Fixed issue #3

### CODE REVIEW

**Comment by Codesait** [comment]
@shatanikmahanty Please review

**Review by shatanikmahanty — CHANGES_REQUESTED** [review]
@Codesait Please add bouncing physics to the mobile view drawer scrollable area and home page why open source sections as well

**Comment by Codesait** [comment]
> @Codesait Please add bouncing physics to the mobile view drawer scrollable area and home page why open source sections as well

Please could you point me to where this changes will be made?

Currently I just figured I omitted :
UserTab
EditProfilePage

and I have added the pay only on this classes but can't find the drawer and open source sections.

**Comment by shatanikmahanty** [comment]
> > @Codesait Please add bouncing physics to the mobile view drawer scrollable area and home page why open source sections as well
> 
> Please could you point me to where this changes will be made?
> 
> Currently I just figured I omitted : UserTab EditProfilePage
> 
> and I have added the pay only on this classes but can't find the drawer and open source sections.

Drawer is present in `lib\widgets\Utils\navigation_drawer.dart` and the open source section is in `lib\widgets\Home\sub_pages\benifits.dart`

**Comment by Codesait** [comment]
> > > @Codesait Please add bouncing physics to the mobile view drawer scrollable area and home page why open source sections as well
> > 
> > 
> > Please could you point me to where this changes will be made?
> > Currently I just figured I omitted : UserTab EditProfilePage
> > and I have added the pay only on this classes but can't find the drawer and open source sections.
> 
> Drawer is present in `lib\widgets\Utils\navigation_drawer.dart` and the open source section is in `lib\widgets\Home\sub_pages\benifits.dart`

Done!
🙂

**Review by shatanikmahanty — APPROVED** [review]
Awesome work. Thanks for your contribution to ocy 😊

**Comment by Codesait** [comment]
> Awesome work. Thanks for your contribution to ocy 😊

Thanks for the opportunity! 🙏🏽

**Pull request merged**
